######################################################################
# Automatically generated by qmake (2.01a) Fri May 22 17:19:08 2015
######################################################################

TEMPLATE = app
TARGET = MRichTextEdit
DEPENDPATH += .
INCLUDEPATH += .

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += mrichtextedit.h mtextedit.h
FORMS += mrichtextedit.ui
SOURCES += mrichtextedit.cpp mtextedit.cpp test.cpp
